# Generated by Django 5.0.4 on 2024-04-14 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientomodel',
            name='consulta',
        ),
        migrations.CreateModel(
            name='TratamientoConsultaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta_api.consultamodel', verbose_name='Consulta')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta_api.tratamientomodel', verbose_name='Tratamiento')),
            ],
            options={
                'verbose_name': 'Tratamiento_Consulta',
                'verbose_name_plural': 'Tratamientos_Consulta',
                'db_table': 'Tratamiento_Consulta',
            },
        ),
    ]
