# Generated by Django 5.0.4 on 2024-04-14 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_api', '0003_remove_consultamodel_paciente_expedientemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamodel',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expediente_Consulta', to='consulta_api.expedientemodel', verbose_name='Expediente'),
        ),
    ]
