# Generated by Django 5.0.4 on 2024-04-14 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_api', '0004_alter_consultamodel_expediente'),
        ('recepcion', '0004_pacientemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientemodel',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.pacientemodel', verbose_name='Paciente'),
        ),
    ]
