# Generated by Django 5.0.4 on 2024-04-17 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_api', '0005_alter_expedientemodel_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientoconsultamodel',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='consulta_api.consultamodel', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='tratamientomodel',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
