# Generated by Django 5.0.4 on 2024-04-20 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consulta_api", "0006_alter_tratamientoconsultamodel_consulta_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.BooleanField(default=False, verbose_name="Estado")),
                ("fecha_emision", models.DateField(verbose_name="Fecha de Emision")),
                ("monto", models.FloatField(verbose_name="Monto")),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consulta_api.consultamodel",
                        verbose_name="Consulra",
                    ),
                ),
                (
                    "recepcionista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recepcionista que Emite la factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "db_table": "Facturas",
            },
        ),
    ]
