# Generated by Django 5.0.4 on 2024-04-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=15, verbose_name="Dni")),
                (
                    "primer_nombre",
                    models.CharField(max_length=75, verbose_name="Primer Nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True,
                        max_length=75,
                        null=True,
                        verbose_name="Segundo Nombre",
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=75, verbose_name="Primer Apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        blank=True,
                        max_length=75,
                        null=True,
                        verbose_name="Segundo Apellido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "db_table": "Persona",
            },
        ),
        migrations.CreateModel(
            name="PacienteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=254, verbose_name="Correo")),
                ("telefono", models.CharField(max_length=15, verbose_name="Telefono")),
                ("fecha_nacimiento", models.DateField(verbose_name="Fecha Nacimiento")),
                (
                    "direccion",
                    models.TextField(max_length=100, verbose_name="Direccion"),
                ),
                ("genero", models.CharField(max_length=1, verbose_name="Genero")),
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes",
                        to="recepcion.personamodel",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "Paciente",
            },
        ),
    ]
