# Generated by Django 5.0.4 on 2024-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepcion", "0002_remove_personamodel_dni"),
    ]

    operations = [
        migrations.AddField(
            model_name="personamodel",
            name="dni",
            field=models.CharField(default=1, max_length=15, verbose_name="Dni"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PacienteModel",
        ),
    ]
