# Generated by Django 5.0.4 on 2024-04-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepcion", "0003_personamodel_dni_delete_pacientemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacienteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=254, verbose_name="Correo")),
                ("telefono", models.CharField(max_length=15, verbose_name="Telefono")),
                ("fecha_nacimiento", models.DateField(verbose_name="Fecha Nacimiento")),
                (
                    "direccion",
                    models.TextField(max_length=100, verbose_name="Direccion"),
                ),
                ("genero", models.CharField(max_length=1, verbose_name="Genero")),
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes",
                        to="recepcion.personamodel",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "Paciente",
            },
        ),
    ]
