# Generated by Django 5.0.4 on 2024-04-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepcion", "0005_alter_personamodel_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacientemodel",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
                verbose_name="Genero",
            ),
        ),
    ]
